version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: myapp-frontend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - myapp-dev-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: myapp-backend-dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    networks:
      - myapp-dev-network

networks:
  myapp-dev-network:
    driver: bridge
