name: ChessCI

on: [ push ]

jobs:
  integration:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node: [ 23 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV

      - name: Git
        uses: actions/checkout@v4

      - name: Setup Node environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Cache node_modules
        uses: actions/cache@v4.2.0
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Run typecheck
        run: npm run type-check

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm run test
