name: ChessCI

on: [ push ]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Git
        uses: actions/checkout@v4

      - name: Setup Node environment
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'

      - name: Cache node_modules
        uses: actions/cache@v4.2.0
        with:
          path: node_modules
          key: ubuntu-latest-node-v23-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Run typecheck
        run: npm run ts

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm run test
